version: '3.8'

services:
  db:
    image: postgres:15
    container_name: telegram_postgres
    restart: always
    environment:
      POSTGRES_DB: userids-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2UolD9i8wNoHBQm1obCwXXlWfQdqcfDe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "bot.py"]

volumes:
  postgres_data:
